# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/models/v1alpha1/space.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'protos/models/v1alpha1/space.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos.models.v1alpha1 import enums_pb2 as protos_dot_models_dot_v1alpha1_dot_enums__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"protos/models/v1alpha1/space.proto\x12\x0fmodels.v1alpha1\x1a\"protos/models/v1alpha1/enums.proto\"\x8d\x01\n\x05Space\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\x12 \n\x0b\x64isplayName\x18\x02 \x01(\tR\x0b\x64isplayName\x12\x18\n\x07spaceId\x18\x03 \x01(\tR\x07spaceId\x12\x14\n\x05users\x18\x04 \x03(\tR\x05users\x12\x1e\n\nownerUsers\x18\x05 \x03(\tR\nownerUsers\"\xc7\x01\n\x04User\x12 \n\x0b\x64isplayName\x18\x01 \x01(\tR\x0b\x64isplayName\x12\x16\n\x06userId\x18\x02 \x01(\tR\x06userId\x12\x14\n\x05\x65mail\x18\x03 \x01(\tR\x05\x65mail\x12\x35\n\x06status\x18\x04 \x01(\x0e\x32\x1d.models.v1alpha1.CommonStatusR\x06status\x12\x1c\n\tfirstName\x18\x05 \x01(\tR\tfirstName\x12\x1a\n\x08lastName\x18\x06 \x01(\tR\x08lastNameB\xc9\x01\n\x13\x63om.models.v1alpha1B\nSpaceProtoP\x01ZIgithub.com/vapusdata-ecosystem/vapusai-studio/apis/protos/models/v1alpha1\xa2\x02\x03MXX\xaa\x02\x0fModels.V1alpha1\xca\x02\x0fModels\\V1alpha1\xe2\x02\x1bModels\\V1alpha1\\GPBMetadata\xea\x02\x10Models::V1alpha1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.models.v1alpha1.space_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023com.models.v1alpha1B\nSpaceProtoP\001ZIgithub.com/vapusdata-ecosystem/vapusai-studio/apis/protos/models/v1alpha1\242\002\003MXX\252\002\017Models.V1alpha1\312\002\017Models\\V1alpha1\342\002\033Models\\V1alpha1\\GPBMetadata\352\002\020Models::V1alpha1'
  _globals['_SPACE']._serialized_start=92
  _globals['_SPACE']._serialized_end=233
  _globals['_USER']._serialized_start=236
  _globals['_USER']._serialized_end=435
# @@protoc_insertion_point(module_scope)
