# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos.vapusai.v1alpha1 import vapusai_pb2 as protos_dot_vapusai_dot_v1alpha1_dot_vapusai__pb2


class VapusAiServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.VapusAiConfigInterface = channel.unary_unary(
                '/aiplane.v1alpha1.VapusAiService/VapusAiConfigInterface',
                request_serializer=protos_dot_vapusai_dot_v1alpha1_dot_vapusai__pb2.VapusAiConfigInterfaceRequest.SerializeToString,
                response_deserializer=protos_dot_vapusai_dot_v1alpha1_dot_vapusai__pb2.VapusAiConfigAgentResponse.FromString,
                _registered_method=True)
        self.VapusAiAgent = channel.unary_unary(
                '/aiplane.v1alpha1.VapusAiService/VapusAiAgent',
                request_serializer=protos_dot_vapusai_dot_v1alpha1_dot_vapusai__pb2.VapusAiAgentRequest.SerializeToString,
                response_deserializer=protos_dot_vapusai_dot_v1alpha1_dot_vapusai__pb2.VapusAiAgentResponse.FromString,
                _registered_method=True)


class VapusAiServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def VapusAiConfigInterface(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VapusAiAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VapusAiServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'VapusAiConfigInterface': grpc.unary_unary_rpc_method_handler(
                    servicer.VapusAiConfigInterface,
                    request_deserializer=protos_dot_vapusai_dot_v1alpha1_dot_vapusai__pb2.VapusAiConfigInterfaceRequest.FromString,
                    response_serializer=protos_dot_vapusai_dot_v1alpha1_dot_vapusai__pb2.VapusAiConfigAgentResponse.SerializeToString,
            ),
            'VapusAiAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.VapusAiAgent,
                    request_deserializer=protos_dot_vapusai_dot_v1alpha1_dot_vapusai__pb2.VapusAiAgentRequest.FromString,
                    response_serializer=protos_dot_vapusai_dot_v1alpha1_dot_vapusai__pb2.VapusAiAgentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aiplane.v1alpha1.VapusAiService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aiplane.v1alpha1.VapusAiService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VapusAiService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def VapusAiConfigInterface(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aiplane.v1alpha1.VapusAiService/VapusAiConfigInterface',
            protos_dot_vapusai_dot_v1alpha1_dot_vapusai__pb2.VapusAiConfigInterfaceRequest.SerializeToString,
            protos_dot_vapusai_dot_v1alpha1_dot_vapusai__pb2.VapusAiConfigAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VapusAiAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aiplane.v1alpha1.VapusAiService/VapusAiAgent',
            protos_dot_vapusai_dot_v1alpha1_dot_vapusai__pb2.VapusAiAgentRequest.SerializeToString,
            protos_dot_vapusai_dot_v1alpha1_dot_vapusai__pb2.VapusAiAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
