//*
// This file defines the protocol buffer messages for the common models in the v1alpha1 version of the API.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: protos/models/v1alpha1/common.proto

package v1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// Represents a search parameter.
type SearchParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Q      string     `protobuf:"bytes,1,opt,name=q,proto3" json:"q,omitempty"`           // The search query string.
	Search []*MapList `protobuf:"bytes,2,rep,name=search,proto3" json:"search,omitempty"` // The list of search parameters.
}

func (x *SearchParam) Reset() {
	*x = SearchParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_models_v1alpha1_common_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchParam) ProtoMessage() {}

func (x *SearchParam) ProtoReflect() protoreflect.Message {
	mi := &file_protos_models_v1alpha1_common_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchParam.ProtoReflect.Descriptor instead.
func (*SearchParam) Descriptor() ([]byte, []int) {
	return file_protos_models_v1alpha1_common_proto_rawDescGZIP(), []int{0}
}

func (x *SearchParam) GetQ() string {
	if x != nil {
		return x.Q
	}
	return ""
}

func (x *SearchParam) GetSearch() []*MapList {
	if x != nil {
		return x.Search
	}
	return nil
}

// *
// Represents a key-value pair for mapping.
type Mapper struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`     // The key.
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"` // The value.
}

func (x *Mapper) Reset() {
	*x = Mapper{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_models_v1alpha1_common_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Mapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mapper) ProtoMessage() {}

func (x *Mapper) ProtoReflect() protoreflect.Message {
	mi := &file_protos_models_v1alpha1_common_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mapper.ProtoReflect.Descriptor instead.
func (*Mapper) Descriptor() ([]byte, []int) {
	return file_protos_models_v1alpha1_common_proto_rawDescGZIP(), []int{1}
}

func (x *Mapper) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Mapper) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// *
// Represents a key-value pair in a map.
type MapList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key    string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`       // The key.
	Values []string `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"` // The list of values.
}

func (x *MapList) Reset() {
	*x = MapList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_models_v1alpha1_common_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MapList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapList) ProtoMessage() {}

func (x *MapList) ProtoReflect() protoreflect.Message {
	mi := &file_protos_models_v1alpha1_common_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapList.ProtoReflect.Descriptor instead.
func (*MapList) Descriptor() ([]byte, []int) {
	return file_protos_models_v1alpha1_common_proto_rawDescGZIP(), []int{2}
}

func (x *MapList) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *MapList) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

// *
// Represents a base identifier.
type BaseIdentifier struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`             // The name.
	Type       string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`             // The type.
	Identifier string `protobuf:"bytes,3,opt,name=identifier,proto3" json:"identifier,omitempty"` // The identifier.
}

func (x *BaseIdentifier) Reset() {
	*x = BaseIdentifier{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_models_v1alpha1_common_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BaseIdentifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseIdentifier) ProtoMessage() {}

func (x *BaseIdentifier) ProtoReflect() protoreflect.Message {
	mi := &file_protos_models_v1alpha1_common_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseIdentifier.ProtoReflect.Descriptor instead.
func (*BaseIdentifier) Descriptor() ([]byte, []int) {
	return file_protos_models_v1alpha1_common_proto_rawDescGZIP(), []int{3}
}

func (x *BaseIdentifier) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BaseIdentifier) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *BaseIdentifier) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

// *
// Represents a synchronization schedule.
type SyncSchedule struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Frequency Frequency `protobuf:"varint,1,opt,name=frequency,proto3,enum=models.v1alpha1.Frequency" json:"frequency,omitempty"` // The frequency of synchronization.
	Value     int64     `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`                                        // The value associated with the frequency.
	Limit     int64     `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`                                        // The limit for synchronization.
}

func (x *SyncSchedule) Reset() {
	*x = SyncSchedule{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_models_v1alpha1_common_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncSchedule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncSchedule) ProtoMessage() {}

func (x *SyncSchedule) ProtoReflect() protoreflect.Message {
	mi := &file_protos_models_v1alpha1_common_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncSchedule.ProtoReflect.Descriptor instead.
func (*SyncSchedule) Descriptor() ([]byte, []int) {
	return file_protos_models_v1alpha1_common_proto_rawDescGZIP(), []int{4}
}

func (x *SyncSchedule) GetFrequency() Frequency {
	if x != nil {
		return x.Frequency
	}
	return Frequency_INVALID_FREQUENCY
}

func (x *SyncSchedule) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *SyncSchedule) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// *
// Represents a schedule tab.
type ScheduleTab struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SyncTab []*SyncSchedule `protobuf:"bytes,1,rep,name=syncTab,proto3" json:"syncTab,omitempty"` // The list of synchronization schedules.
	Limit   int64           `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`    // The limit for the schedule tab.
}

func (x *ScheduleTab) Reset() {
	*x = ScheduleTab{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_models_v1alpha1_common_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScheduleTab) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleTab) ProtoMessage() {}

func (x *ScheduleTab) ProtoReflect() protoreflect.Message {
	mi := &file_protos_models_v1alpha1_common_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleTab.ProtoReflect.Descriptor instead.
func (*ScheduleTab) Descriptor() ([]byte, []int) {
	return file_protos_models_v1alpha1_common_proto_rawDescGZIP(), []int{5}
}

func (x *ScheduleTab) GetSyncTab() []*SyncSchedule {
	if x != nil {
		return x.SyncTab
	}
	return nil
}

func (x *ScheduleTab) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// *
// Represents the parameters for JWT authentication.
type JWTParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name                string         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                                              // The name.
	PublicJWTKey        string         `protobuf:"bytes,2,opt,name=publicJWTKey,proto3" json:"publicJWTKey,omitempty"`                                              // The public JWT key.
	PrivateJWTKey       string         `protobuf:"bytes,3,opt,name=privateJWTKey,proto3" json:"privateJWTKey,omitempty"`                                            // The private JWT key.
	VId                 string         `protobuf:"bytes,4,opt,name=vId,proto3" json:"vId,omitempty"`                                                                // Ignore in Requests
	SigningAlgorithm    EncryptionAlgo `protobuf:"varint,5,opt,name=signingAlgorithm,proto3,enum=models.v1alpha1.EncryptionAlgo" json:"signingAlgorithm,omitempty"` // The signing algorithm.
	IsAlreadyInSecretBS bool           `protobuf:"varint,6,opt,name=isAlreadyInSecretBS,proto3" json:"isAlreadyInSecretBS,omitempty"`                               // Indicates if the JWT keys are already in the secret base store.
	Status              CommonStatus   `protobuf:"varint,7,opt,name=status,proto3,enum=models.v1alpha1.CommonStatus" json:"status,omitempty"`                       // The status.
	GenerateInPlatform  bool           `protobuf:"varint,8,opt,name=generateInPlatform,proto3" json:"generateInPlatform,omitempty"`                                 // Indicates if the JWT keys should be generated in the platform.
}

func (x *JWTParams) Reset() {
	*x = JWTParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_models_v1alpha1_common_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JWTParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JWTParams) ProtoMessage() {}

func (x *JWTParams) ProtoReflect() protoreflect.Message {
	mi := &file_protos_models_v1alpha1_common_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JWTParams.ProtoReflect.Descriptor instead.
func (*JWTParams) Descriptor() ([]byte, []int) {
	return file_protos_models_v1alpha1_common_proto_rawDescGZIP(), []int{6}
}

func (x *JWTParams) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *JWTParams) GetPublicJWTKey() string {
	if x != nil {
		return x.PublicJWTKey
	}
	return ""
}

func (x *JWTParams) GetPrivateJWTKey() string {
	if x != nil {
		return x.PrivateJWTKey
	}
	return ""
}

func (x *JWTParams) GetVId() string {
	if x != nil {
		return x.VId
	}
	return ""
}

func (x *JWTParams) GetSigningAlgorithm() EncryptionAlgo {
	if x != nil {
		return x.SigningAlgorithm
	}
	return EncryptionAlgo_JSA_INVALID
}

func (x *JWTParams) GetIsAlreadyInSecretBS() bool {
	if x != nil {
		return x.IsAlreadyInSecretBS
	}
	return false
}

func (x *JWTParams) GetStatus() CommonStatus {
	if x != nil {
		return x.Status
	}
	return CommonStatus_INVALID_STATUS
}

func (x *JWTParams) GetGenerateInPlatform() bool {
	if x != nil {
		return x.GenerateInPlatform
	}
	return false
}

// *
// Represents the TLS configuration.
type TlsConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TlsType        TlsType `protobuf:"varint,1,opt,name=tlsType,proto3,enum=models.v1alpha1.TlsType" json:"tlsType,omitempty"` // The type of TLS.
	CaCertFile     string  `protobuf:"bytes,2,opt,name=caCertFile,proto3" json:"caCertFile,omitempty"`                         // The CA certificate file.
	ServerKeyFile  string  `protobuf:"bytes,3,opt,name=serverKeyFile,proto3" json:"serverKeyFile,omitempty"`                   // The server key file.
	ServerCertFile string  `protobuf:"bytes,4,opt,name=serverCertFile,proto3" json:"serverCertFile,omitempty"`                 // The server certificate file.
}

func (x *TlsConfig) Reset() {
	*x = TlsConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_models_v1alpha1_common_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TlsConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TlsConfig) ProtoMessage() {}

func (x *TlsConfig) ProtoReflect() protoreflect.Message {
	mi := &file_protos_models_v1alpha1_common_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TlsConfig.ProtoReflect.Descriptor instead.
func (*TlsConfig) Descriptor() ([]byte, []int) {
	return file_protos_models_v1alpha1_common_proto_rawDescGZIP(), []int{7}
}

func (x *TlsConfig) GetTlsType() TlsType {
	if x != nil {
		return x.TlsType
	}
	return TlsType_INSECURE
}

func (x *TlsConfig) GetCaCertFile() string {
	if x != nil {
		return x.CaCertFile
	}
	return ""
}

func (x *TlsConfig) GetServerKeyFile() string {
	if x != nil {
		return x.ServerKeyFile
	}
	return ""
}

func (x *TlsConfig) GetServerCertFile() string {
	if x != nil {
		return x.ServerCertFile
	}
	return ""
}

// *
// Represents the SSL certificates.
type SSLCerts struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SslCert             string       `protobuf:"bytes,1,opt,name=sslCert,proto3" json:"sslCert,omitempty"`                                  // The SSL certificate.
	SslKey              string       `protobuf:"bytes,2,opt,name=sslKey,proto3" json:"sslKey,omitempty"`                                    // The SSL key.
	VId                 string       `protobuf:"bytes,3,opt,name=vId,proto3" json:"vId,omitempty"`                                          // Ignore in Requests
	IsAlreadyInSecretBS bool         `protobuf:"varint,4,opt,name=isAlreadyInSecretBS,proto3" json:"isAlreadyInSecretBS,omitempty"`         // Indicates if the SSL certificates are already in the secret base store.
	Status              CommonStatus `protobuf:"varint,5,opt,name=status,proto3,enum=models.v1alpha1.CommonStatus" json:"status,omitempty"` // The status.
}

func (x *SSLCerts) Reset() {
	*x = SSLCerts{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_models_v1alpha1_common_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SSLCerts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSLCerts) ProtoMessage() {}

func (x *SSLCerts) ProtoReflect() protoreflect.Message {
	mi := &file_protos_models_v1alpha1_common_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSLCerts.ProtoReflect.Descriptor instead.
func (*SSLCerts) Descriptor() ([]byte, []int) {
	return file_protos_models_v1alpha1_common_proto_rawDescGZIP(), []int{8}
}

func (x *SSLCerts) GetSslCert() string {
	if x != nil {
		return x.SslCert
	}
	return ""
}

func (x *SSLCerts) GetSslKey() string {
	if x != nil {
		return x.SslKey
	}
	return ""
}

func (x *SSLCerts) GetVId() string {
	if x != nil {
		return x.VId
	}
	return ""
}

func (x *SSLCerts) GetIsAlreadyInSecretBS() bool {
	if x != nil {
		return x.IsAlreadyInSecretBS
	}
	return false
}

func (x *SSLCerts) GetStatus() CommonStatus {
	if x != nil {
		return x.Status
	}
	return CommonStatus_INVALID_STATUS
}

// *
// Represents the response from the data manager.
type DMResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message       string        `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`             // The message.
	DmStatusCode  string        `protobuf:"bytes,2,opt,name=dmStatusCode,proto3" json:"dmStatusCode,omitempty"`   // The data manager status code.
	CustomMessage []*MapList    `protobuf:"bytes,3,rep,name=customMessage,proto3" json:"customMessage,omitempty"` // The list of custom messages.
	Agents        []*AgentShort `protobuf:"bytes,4,rep,name=agents,proto3" json:"agents,omitempty"`               // The list of agents.
}

func (x *DMResponse) Reset() {
	*x = DMResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_models_v1alpha1_common_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DMResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DMResponse) ProtoMessage() {}

func (x *DMResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_models_v1alpha1_common_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DMResponse.ProtoReflect.Descriptor instead.
func (*DMResponse) Descriptor() ([]byte, []int) {
	return file_protos_models_v1alpha1_common_proto_rawDescGZIP(), []int{9}
}

func (x *DMResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DMResponse) GetDmStatusCode() string {
	if x != nil {
		return x.DmStatusCode
	}
	return ""
}

func (x *DMResponse) GetCustomMessage() []*MapList {
	if x != nil {
		return x.CustomMessage
	}
	return nil
}

func (x *DMResponse) GetAgents() []*AgentShort {
	if x != nil {
		return x.Agents
	}
	return nil
}

// *
// Represents a short version of an agent.
type AgentShort struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Agent      string   `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`           // The agent.
	AgentType  string   `protobuf:"bytes,2,opt,name=agentType,proto3" json:"agentType,omitempty"`   // The agent type.
	GoalStatus string   `protobuf:"bytes,3,opt,name=goalStatus,proto3" json:"goalStatus,omitempty"` // The goal status.
	Error      []string `protobuf:"bytes,4,rep,name=error,proto3" json:"error,omitempty"`           // The list of errors.
	Result     string   `protobuf:"bytes,5,opt,name=result,proto3" json:"result,omitempty"`         // The result.
}

func (x *AgentShort) Reset() {
	*x = AgentShort{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_models_v1alpha1_common_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentShort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentShort) ProtoMessage() {}

func (x *AgentShort) ProtoReflect() protoreflect.Message {
	mi := &file_protos_models_v1alpha1_common_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentShort.ProtoReflect.Descriptor instead.
func (*AgentShort) Descriptor() ([]byte, []int) {
	return file_protos_models_v1alpha1_common_proto_rawDescGZIP(), []int{10}
}

func (x *AgentShort) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

func (x *AgentShort) GetAgentType() string {
	if x != nil {
		return x.AgentType
	}
	return ""
}

func (x *AgentShort) GetGoalStatus() string {
	if x != nil {
		return x.GoalStatus
	}
	return ""
}

func (x *AgentShort) GetError() []string {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *AgentShort) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

// *
// Represents a dynamic message.
type DynamicMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DynamicMessage) Reset() {
	*x = DynamicMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_models_v1alpha1_common_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DynamicMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DynamicMessage) ProtoMessage() {}

func (x *DynamicMessage) ProtoReflect() protoreflect.Message {
	mi := &file_protos_models_v1alpha1_common_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DynamicMessage.ProtoReflect.Descriptor instead.
func (*DynamicMessage) Descriptor() ([]byte, []int) {
	return file_protos_models_v1alpha1_common_proto_rawDescGZIP(), []int{11}
}

// *
// Represents an update to a dynamic message.
type DynamicMessageUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Body *DynamicMessage `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"` // The body of the dynamic message.
}

func (x *DynamicMessageUpdate) Reset() {
	*x = DynamicMessageUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_models_v1alpha1_common_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DynamicMessageUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DynamicMessageUpdate) ProtoMessage() {}

func (x *DynamicMessageUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_protos_models_v1alpha1_common_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DynamicMessageUpdate.ProtoReflect.Descriptor instead.
func (*DynamicMessageUpdate) Descriptor() ([]byte, []int) {
	return file_protos_models_v1alpha1_common_proto_rawDescGZIP(), []int{12}
}

func (x *DynamicMessageUpdate) GetBody() *DynamicMessage {
	if x != nil {
		return x.Body
	}
	return nil
}

// *
// Represents the vapus credentials.
type VapusCredentials struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username     string       `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`                                            // The username.
	Password     string       `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`                                            // The password.
	ApiToken     string       `protobuf:"bytes,3,opt,name=apiToken,proto3" json:"apiToken,omitempty"`                                            // The API token.
	ApiTokenType ApiTokenType `protobuf:"varint,4,opt,name=apiTokenType,proto3,enum=models.v1alpha1.ApiTokenType" json:"apiTokenType,omitempty"` // The type of API token.
	AwsCreds     *AWSCreds    `protobuf:"bytes,5,opt,name=awsCreds,proto3" json:"awsCreds,omitempty"`                                            // The AWS credentials.
	GcpCreds     *GCPCreds    `protobuf:"bytes,6,opt,name=gcpCreds,proto3" json:"gcpCreds,omitempty"`                                            // The GCP credentials.
	AzureCreds   *AzureCreds  `protobuf:"bytes,7,opt,name=azureCreds,proto3" json:"azureCreds,omitempty"`                                        // The Azure credentials.
}

func (x *VapusCredentials) Reset() {
	*x = VapusCredentials{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_models_v1alpha1_common_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VapusCredentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VapusCredentials) ProtoMessage() {}

func (x *VapusCredentials) ProtoReflect() protoreflect.Message {
	mi := &file_protos_models_v1alpha1_common_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VapusCredentials.ProtoReflect.Descriptor instead.
func (*VapusCredentials) Descriptor() ([]byte, []int) {
	return file_protos_models_v1alpha1_common_proto_rawDescGZIP(), []int{13}
}

func (x *VapusCredentials) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *VapusCredentials) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *VapusCredentials) GetApiToken() string {
	if x != nil {
		return x.ApiToken
	}
	return ""
}

func (x *VapusCredentials) GetApiTokenType() ApiTokenType {
	if x != nil {
		return x.ApiTokenType
	}
	return ApiTokenType_BASIC
}

func (x *VapusCredentials) GetAwsCreds() *AWSCreds {
	if x != nil {
		return x.AwsCreds
	}
	return nil
}

func (x *VapusCredentials) GetGcpCreds() *GCPCreds {
	if x != nil {
		return x.GcpCreds
	}
	return nil
}

func (x *VapusCredentials) GetAzureCreds() *AzureCreds {
	if x != nil {
		return x.AzureCreds
	}
	return nil
}

// *
// Represents the AWS credentials.
type AWSCreds struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccessKeyId     string `protobuf:"bytes,1,opt,name=accessKeyId,proto3" json:"accessKeyId,omitempty"`         // The AWS access key ID.
	SecretAccessKey string `protobuf:"bytes,2,opt,name=secretAccessKey,proto3" json:"secretAccessKey,omitempty"` // The AWS secret access key.
	Region          string `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`                   // The AWS region.
	SessionToken    string `protobuf:"bytes,4,opt,name=sessionToken,proto3" json:"sessionToken,omitempty"`       // The AWS session token.
}

func (x *AWSCreds) Reset() {
	*x = AWSCreds{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_models_v1alpha1_common_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AWSCreds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AWSCreds) ProtoMessage() {}

func (x *AWSCreds) ProtoReflect() protoreflect.Message {
	mi := &file_protos_models_v1alpha1_common_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AWSCreds.ProtoReflect.Descriptor instead.
func (*AWSCreds) Descriptor() ([]byte, []int) {
	return file_protos_models_v1alpha1_common_proto_rawDescGZIP(), []int{14}
}

func (x *AWSCreds) GetAccessKeyId() string {
	if x != nil {
		return x.AccessKeyId
	}
	return ""
}

func (x *AWSCreds) GetSecretAccessKey() string {
	if x != nil {
		return x.SecretAccessKey
	}
	return ""
}

func (x *AWSCreds) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *AWSCreds) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

// *
// Represents the GCP credentials.
type GCPCreds struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServiceAccountKey string `protobuf:"bytes,1,opt,name=serviceAccountKey,proto3" json:"serviceAccountKey,omitempty"` // The GCP service account key.
	Base64Encoded     bool   `protobuf:"varint,2,opt,name=base64Encoded,proto3" json:"base64Encoded,omitempty"`        // Indicates if the service account key is base64 encoded.
	Region            string `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`                       // The GCP region.
	ProjectId         string `protobuf:"bytes,4,opt,name=projectId,proto3" json:"projectId,omitempty"`                 // The GCP project ID.
	Zone              string `protobuf:"bytes,5,opt,name=zone,proto3" json:"zone,omitempty"`                           // The GCP zone.
}

func (x *GCPCreds) Reset() {
	*x = GCPCreds{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_models_v1alpha1_common_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GCPCreds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GCPCreds) ProtoMessage() {}

func (x *GCPCreds) ProtoReflect() protoreflect.Message {
	mi := &file_protos_models_v1alpha1_common_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GCPCreds.ProtoReflect.Descriptor instead.
func (*GCPCreds) Descriptor() ([]byte, []int) {
	return file_protos_models_v1alpha1_common_proto_rawDescGZIP(), []int{15}
}

func (x *GCPCreds) GetServiceAccountKey() string {
	if x != nil {
		return x.ServiceAccountKey
	}
	return ""
}

func (x *GCPCreds) GetBase64Encoded() bool {
	if x != nil {
		return x.Base64Encoded
	}
	return false
}

func (x *GCPCreds) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *GCPCreds) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *GCPCreds) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

// *
// Represents the Azure credentials.
type AzureCreds struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TenantId     string `protobuf:"bytes,1,opt,name=tenantId,proto3" json:"tenantId,omitempty"`         // The Azure tenant ID.
	ClientId     string `protobuf:"bytes,2,opt,name=clientId,proto3" json:"clientId,omitempty"`         // The Azure client ID.
	ClientSecret string `protobuf:"bytes,3,opt,name=clientSecret,proto3" json:"clientSecret,omitempty"` // The Azure client secret.
}

func (x *AzureCreds) Reset() {
	*x = AzureCreds{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_models_v1alpha1_common_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AzureCreds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AzureCreds) ProtoMessage() {}

func (x *AzureCreds) ProtoReflect() protoreflect.Message {
	mi := &file_protos_models_v1alpha1_common_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AzureCreds.ProtoReflect.Descriptor instead.
func (*AzureCreds) Descriptor() ([]byte, []int) {
	return file_protos_models_v1alpha1_common_proto_rawDescGZIP(), []int{16}
}

func (x *AzureCreds) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *AzureCreds) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *AzureCreds) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

// *
// Represents a digest value.
type DigestVal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Algo   HashAlgos `protobuf:"varint,1,opt,name=algo,proto3,enum=models.v1alpha1.HashAlgos" json:"algo,omitempty"` // The hash algorithm.
	Digest string    `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`                             // The digest value.
}

func (x *DigestVal) Reset() {
	*x = DigestVal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_models_v1alpha1_common_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DigestVal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DigestVal) ProtoMessage() {}

func (x *DigestVal) ProtoReflect() protoreflect.Message {
	mi := &file_protos_models_v1alpha1_common_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DigestVal.ProtoReflect.Descriptor instead.
func (*DigestVal) Descriptor() ([]byte, []int) {
	return file_protos_models_v1alpha1_common_proto_rawDescGZIP(), []int{17}
}

func (x *DigestVal) GetAlgo() HashAlgos {
	if x != nil {
		return x.Algo
	}
	return HashAlgos_INVALID_HASH_ALGO
}

func (x *DigestVal) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

// *
// Represents an empty request.
type EmptyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EmptyRequest) Reset() {
	*x = EmptyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_models_v1alpha1_common_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmptyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyRequest) ProtoMessage() {}

func (x *EmptyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_models_v1alpha1_common_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyRequest.ProtoReflect.Descriptor instead.
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return file_protos_models_v1alpha1_common_proto_rawDescGZIP(), []int{18}
}

// *
// Represents the OIDC authentication parameters.
type AuthnOIDC struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Callback            string       `protobuf:"bytes,1,opt,name=callback,proto3" json:"callback,omitempty"`                                // The OIDC callback URL.
	ClientId            string       `protobuf:"bytes,2,opt,name=clientId,proto3" json:"clientId,omitempty"`                                // The OIDC client ID.
	ClientSecret        string       `protobuf:"bytes,3,opt,name=clientSecret,proto3" json:"clientSecret,omitempty"`                        // The OIDC client secret.
	VId                 string       `protobuf:"bytes,4,opt,name=vId,proto3" json:"vId,omitempty" yaml:"vId"`                                          //@gotags: yaml:"vId"
	IsAlreadyInSecretBS bool         `protobuf:"varint,5,opt,name=isAlreadyInSecretBS,proto3" json:"isAlreadyInSecretBS,omitempty"`         // Indicates if the OIDC client credentials are already in the secret base store.
	Status              CommonStatus `protobuf:"varint,6,opt,name=status,proto3,enum=models.v1alpha1.CommonStatus" json:"status,omitempty"` // The status.
}

func (x *AuthnOIDC) Reset() {
	*x = AuthnOIDC{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_models_v1alpha1_common_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthnOIDC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthnOIDC) ProtoMessage() {}

func (x *AuthnOIDC) ProtoReflect() protoreflect.Message {
	mi := &file_protos_models_v1alpha1_common_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthnOIDC.ProtoReflect.Descriptor instead.
func (*AuthnOIDC) Descriptor() ([]byte, []int) {
	return file_protos_models_v1alpha1_common_proto_rawDescGZIP(), []int{19}
}

func (x *AuthnOIDC) GetCallback() string {
	if x != nil {
		return x.Callback
	}
	return ""
}

func (x *AuthnOIDC) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *AuthnOIDC) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

func (x *AuthnOIDC) GetVId() string {
	if x != nil {
		return x.VId
	}
	return ""
}

func (x *AuthnOIDC) GetIsAlreadyInSecretBS() bool {
	if x != nil {
		return x.IsAlreadyInSecretBS
	}
	return false
}

func (x *AuthnOIDC) GetStatus() CommonStatus {
	if x != nil {
		return x.Status
	}
	return CommonStatus_INVALID_STATUS
}

// *
// Represents a log entry.
type Logs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time    int64  `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`      // The timestamp of the log entry.
	HTime   string `protobuf:"bytes,2,opt,name=hTime,proto3" json:"hTime,omitempty"`     // The human-readable timestamp of the log entry.
	LogType string `protobuf:"bytes,3,opt,name=logType,proto3" json:"logType,omitempty"` // The type of log entry.
	Message string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"` // The log message.
}

func (x *Logs) Reset() {
	*x = Logs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_models_v1alpha1_common_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Logs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Logs) ProtoMessage() {}

func (x *Logs) ProtoReflect() protoreflect.Message {
	mi := &file_protos_models_v1alpha1_common_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Logs.ProtoReflect.Descriptor instead.
func (*Logs) Descriptor() ([]byte, []int) {
	return file_protos_models_v1alpha1_common_proto_rawDescGZIP(), []int{20}
}

func (x *Logs) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *Logs) GetHTime() string {
	if x != nil {
		return x.HTime
	}
	return ""
}

func (x *Logs) GetLogType() string {
	if x != nil {
		return x.LogType
	}
	return ""
}

func (x *Logs) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_protos_models_v1alpha1_common_proto protoreflect.FileDescriptor

var file_protos_models_v1alpha1_common_proto_rawDesc = []byte{
	0x0a, 0x23, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f,
	0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x76, 0x31,
	0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x1a, 0x22, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2f, 0x65,
	0x6e, 0x75, 0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4d, 0x0a, 0x0b, 0x53, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x0c, 0x0a, 0x01, 0x71, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x71, 0x12, 0x30, 0x0a, 0x06, 0x73, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73,
	0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x4d, 0x61, 0x70, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x06, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x22, 0x30, 0x0a, 0x06, 0x4d, 0x61, 0x70,
	0x70, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x33, 0x0a, 0x07, 0x4d,
	0x61, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73,
	0x22, 0x58, 0x0a, 0x0e, 0x42, 0x61, 0x73, 0x65, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69,
	0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x22, 0x74, 0x0a, 0x0c, 0x53, 0x79,
	0x6e, 0x63, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x12, 0x38, 0x0a, 0x09, 0x66, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e,
	0x46, 0x72, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x79, 0x52, 0x09, 0x66, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x6e, 0x63, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69,
	0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74,
	0x22, 0x5c, 0x0a, 0x0b, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x54, 0x61, 0x62, 0x12,
	0x37, 0x0a, 0x07, 0x73, 0x79, 0x6e, 0x63, 0x54, 0x61, 0x62, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1d, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68,
	0x61, 0x31, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x52,
	0x07, 0x73, 0x79, 0x6e, 0x63, 0x54, 0x61, 0x62, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0xe1,
	0x02, 0x0a, 0x09, 0x4a, 0x57, 0x54, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x22, 0x0a, 0x0c, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4a, 0x57, 0x54, 0x4b, 0x65, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4a, 0x57,
	0x54, 0x4b, 0x65, 0x79, 0x12, 0x24, 0x0a, 0x0d, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4a,
	0x57, 0x54, 0x4b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x70, 0x72, 0x69,
	0x76, 0x61, 0x74, 0x65, 0x4a, 0x57, 0x54, 0x4b, 0x65, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x76, 0x49,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x76, 0x49, 0x64, 0x12, 0x4b, 0x0a, 0x10,
	0x73, 0x69, 0x67, 0x6e, 0x69, 0x6e, 0x67, 0x41, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1f, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e,
	0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x41, 0x6c, 0x67, 0x6f, 0x52, 0x10, 0x73, 0x69, 0x67, 0x6e, 0x69, 0x6e, 0x67,
	0x41, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d, 0x12, 0x30, 0x0a, 0x13, 0x69, 0x73, 0x41,
	0x6c, 0x72, 0x65, 0x61, 0x64, 0x79, 0x49, 0x6e, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x42, 0x53,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x13, 0x69, 0x73, 0x41, 0x6c, 0x72, 0x65, 0x61, 0x64,
	0x79, 0x49, 0x6e, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x42, 0x53, 0x12, 0x35, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x73, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x43, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x2e, 0x0a, 0x12, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x49, 0x6e,
	0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x12,
	0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f,
	0x72, 0x6d, 0x22, 0xad, 0x01, 0x0a, 0x09, 0x54, 0x6c, 0x73, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x12, 0x32, 0x0a, 0x07, 0x74, 0x6c, 0x73, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x18, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70,
	0x68, 0x61, 0x31, 0x2e, 0x54, 0x6c, 0x73, 0x54, 0x79, 0x70, 0x65, 0x52, 0x07, 0x74, 0x6c, 0x73,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x61, 0x43, 0x65, 0x72, 0x74, 0x46, 0x69,
	0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x61, 0x43, 0x65, 0x72, 0x74,
	0x46, 0x69, 0x6c, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4b, 0x65,
	0x79, 0x46, 0x69, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x4b, 0x65, 0x79, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x43, 0x65, 0x72, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x43, 0x65, 0x72, 0x74, 0x46, 0x69,
	0x6c, 0x65, 0x22, 0xb7, 0x01, 0x0a, 0x08, 0x53, 0x53, 0x4c, 0x43, 0x65, 0x72, 0x74, 0x73, 0x12,
	0x18, 0x0a, 0x07, 0x73, 0x73, 0x6c, 0x43, 0x65, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x73, 0x73, 0x6c, 0x43, 0x65, 0x72, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x73, 0x6c,
	0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x73, 0x6c, 0x4b, 0x65,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x76, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x76, 0x49, 0x64, 0x12, 0x30, 0x0a, 0x13, 0x69, 0x73, 0x41, 0x6c, 0x72, 0x65, 0x61, 0x64, 0x79,
	0x49, 0x6e, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x42, 0x53, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x13, 0x69, 0x73, 0x41, 0x6c, 0x72, 0x65, 0x61, 0x64, 0x79, 0x49, 0x6e, 0x53, 0x65, 0x63,
	0x72, 0x65, 0x74, 0x42, 0x53, 0x12, 0x35, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x76,
	0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0xbf, 0x01, 0x0a,
	0x0a, 0x44, 0x4d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x64, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x64, 0x6d, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x3e, 0x0a, 0x0d, 0x63, 0x75, 0x73,
	0x74, 0x6f, 0x6d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x18, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68,
	0x61, 0x31, 0x2e, 0x4d, 0x61, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x0d, 0x63, 0x75, 0x73, 0x74,
	0x6f, 0x6d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x33, 0x0a, 0x06, 0x61, 0x67, 0x65,
	0x6e, 0x74, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x73, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x41, 0x67, 0x65, 0x6e,
	0x74, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x52, 0x06, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x8e,
	0x01, 0x0a, 0x0a, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x67,
	0x65, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x67, 0x6f, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x67, 0x6f, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22,
	0x10, 0x0a, 0x0e, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x22, 0x4b, 0x0a, 0x14, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x33, 0x0a, 0x04, 0x62, 0x6f, 0x64,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73,
	0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69,
	0x63, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0xd4,
	0x02, 0x0a, 0x10, 0x56, 0x61, 0x70, 0x75, 0x73, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x61, 0x6c, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x61,
	0x70, 0x69, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61,
	0x70, 0x69, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x41, 0x0a, 0x0c, 0x61, 0x70, 0x69, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e,
	0x41, 0x70, 0x69, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0c, 0x61, 0x70,
	0x69, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x35, 0x0a, 0x08, 0x61, 0x77,
	0x73, 0x43, 0x72, 0x65, 0x64, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x41,
	0x57, 0x53, 0x43, 0x72, 0x65, 0x64, 0x73, 0x52, 0x08, 0x61, 0x77, 0x73, 0x43, 0x72, 0x65, 0x64,
	0x73, 0x12, 0x35, 0x0a, 0x08, 0x67, 0x63, 0x70, 0x43, 0x72, 0x65, 0x64, 0x73, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x76, 0x31, 0x61,
	0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x47, 0x43, 0x50, 0x43, 0x72, 0x65, 0x64, 0x73, 0x52, 0x08,
	0x67, 0x63, 0x70, 0x43, 0x72, 0x65, 0x64, 0x73, 0x12, 0x3b, 0x0a, 0x0a, 0x61, 0x7a, 0x75, 0x72,
	0x65, 0x43, 0x72, 0x65, 0x64, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x41,
	0x7a, 0x75, 0x72, 0x65, 0x43, 0x72, 0x65, 0x64, 0x73, 0x52, 0x0a, 0x61, 0x7a, 0x75, 0x72, 0x65,
	0x43, 0x72, 0x65, 0x64, 0x73, 0x22, 0x92, 0x01, 0x0a, 0x08, 0x41, 0x57, 0x53, 0x43, 0x72, 0x65,
	0x64, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4b, 0x65, 0x79, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4b,
	0x65, 0x79, 0x49, 0x64, 0x12, 0x28, 0x0a, 0x0f, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x41, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x73,
	0x65, 0x63, 0x72, 0x65, 0x74, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4b, 0x65, 0x79, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x22, 0x0a, 0x0c, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0xa8, 0x01, 0x0a, 0x08, 0x47,
	0x43, 0x50, 0x43, 0x72, 0x65, 0x64, 0x73, 0x12, 0x2c, 0x0a, 0x11, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x11, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x4b, 0x65, 0x79, 0x12, 0x24, 0x0a, 0x0d, 0x62, 0x61, 0x73, 0x65, 0x36, 0x34, 0x45,
	0x6e, 0x63, 0x6f, 0x64, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x62, 0x61,
	0x73, 0x65, 0x36, 0x34, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72,
	0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x67,
	0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x49,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x7a, 0x6f, 0x6e, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x7a, 0x6f, 0x6e, 0x65, 0x22, 0x68, 0x0a, 0x0a, 0x41, 0x7a, 0x75, 0x72, 0x65, 0x43, 0x72,
	0x65, 0x64, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x22,
	0x53, 0x0a, 0x09, 0x44, 0x69, 0x67, 0x65, 0x73, 0x74, 0x56, 0x61, 0x6c, 0x12, 0x2e, 0x0a, 0x04,
	0x61, 0x6c, 0x67, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x73, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x48, 0x61, 0x73,
	0x68, 0x41, 0x6c, 0x67, 0x6f, 0x73, 0x52, 0x04, 0x61, 0x6c, 0x67, 0x6f, 0x12, 0x16, 0x0a, 0x06,
	0x64, 0x69, 0x67, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x69,
	0x67, 0x65, 0x73, 0x74, 0x22, 0x0e, 0x0a, 0x0c, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0xe2, 0x01, 0x0a, 0x09, 0x41, 0x75, 0x74, 0x68, 0x6e, 0x4f, 0x49,
	0x44, 0x43, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x12, 0x1a,
	0x0a, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x76, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x76, 0x49, 0x64,
	0x12, 0x30, 0x0a, 0x13, 0x69, 0x73, 0x41, 0x6c, 0x72, 0x65, 0x61, 0x64, 0x79, 0x49, 0x6e, 0x53,
	0x65, 0x63, 0x72, 0x65, 0x74, 0x42, 0x53, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x13, 0x69,
	0x73, 0x41, 0x6c, 0x72, 0x65, 0x61, 0x64, 0x79, 0x49, 0x6e, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74,
	0x42, 0x53, 0x12, 0x35, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x76, 0x31, 0x61, 0x6c,
	0x70, 0x68, 0x61, 0x31, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x64, 0x0a, 0x04, 0x4c, 0x6f, 0x67,
	0x73, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x68, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x68, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6c,
	0x6f, 0x67, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6c, 0x6f,
	0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42,
	0xca, 0x01, 0x0a, 0x13, 0x63, 0x6f, 0x6d, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x76,
	0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x42, 0x0b, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x49, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x76, 0x61, 0x70, 0x75, 0x73, 0x64, 0x61, 0x74, 0x61, 0x2d, 0x65, 0x63, 0x6f,
	0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2f, 0x76, 0x61, 0x70, 0x75, 0x73, 0x61, 0x69, 0x2d, 0x73,
	0x74, 0x75, 0x64, 0x69, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61,
	0x31, 0xa2, 0x02, 0x03, 0x4d, 0x58, 0x58, 0xaa, 0x02, 0x0f, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x73,
	0x2e, 0x56, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0xca, 0x02, 0x0f, 0x4d, 0x6f, 0x64, 0x65,
	0x6c, 0x73, 0x5c, 0x56, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0xe2, 0x02, 0x1b, 0x4d, 0x6f,
	0x64, 0x65, 0x6c, 0x73, 0x5c, 0x56, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x5c, 0x47, 0x50,
	0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x10, 0x4d, 0x6f, 0x64, 0x65,
	0x6c, 0x73, 0x3a, 0x3a, 0x56, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_models_v1alpha1_common_proto_rawDescOnce sync.Once
	file_protos_models_v1alpha1_common_proto_rawDescData = file_protos_models_v1alpha1_common_proto_rawDesc
)

func file_protos_models_v1alpha1_common_proto_rawDescGZIP() []byte {
	file_protos_models_v1alpha1_common_proto_rawDescOnce.Do(func() {
		file_protos_models_v1alpha1_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_models_v1alpha1_common_proto_rawDescData)
	})
	return file_protos_models_v1alpha1_common_proto_rawDescData
}

var file_protos_models_v1alpha1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_protos_models_v1alpha1_common_proto_goTypes = []any{
	(*SearchParam)(nil),          // 0: models.v1alpha1.SearchParam
	(*Mapper)(nil),               // 1: models.v1alpha1.Mapper
	(*MapList)(nil),              // 2: models.v1alpha1.MapList
	(*BaseIdentifier)(nil),       // 3: models.v1alpha1.BaseIdentifier
	(*SyncSchedule)(nil),         // 4: models.v1alpha1.SyncSchedule
	(*ScheduleTab)(nil),          // 5: models.v1alpha1.ScheduleTab
	(*JWTParams)(nil),            // 6: models.v1alpha1.JWTParams
	(*TlsConfig)(nil),            // 7: models.v1alpha1.TlsConfig
	(*SSLCerts)(nil),             // 8: models.v1alpha1.SSLCerts
	(*DMResponse)(nil),           // 9: models.v1alpha1.DMResponse
	(*AgentShort)(nil),           // 10: models.v1alpha1.AgentShort
	(*DynamicMessage)(nil),       // 11: models.v1alpha1.DynamicMessage
	(*DynamicMessageUpdate)(nil), // 12: models.v1alpha1.DynamicMessageUpdate
	(*VapusCredentials)(nil),     // 13: models.v1alpha1.VapusCredentials
	(*AWSCreds)(nil),             // 14: models.v1alpha1.AWSCreds
	(*GCPCreds)(nil),             // 15: models.v1alpha1.GCPCreds
	(*AzureCreds)(nil),           // 16: models.v1alpha1.AzureCreds
	(*DigestVal)(nil),            // 17: models.v1alpha1.DigestVal
	(*EmptyRequest)(nil),         // 18: models.v1alpha1.EmptyRequest
	(*AuthnOIDC)(nil),            // 19: models.v1alpha1.AuthnOIDC
	(*Logs)(nil),                 // 20: models.v1alpha1.Logs
	(Frequency)(0),               // 21: models.v1alpha1.Frequency
	(EncryptionAlgo)(0),          // 22: models.v1alpha1.EncryptionAlgo
	(CommonStatus)(0),            // 23: models.v1alpha1.CommonStatus
	(TlsType)(0),                 // 24: models.v1alpha1.TlsType
	(ApiTokenType)(0),            // 25: models.v1alpha1.ApiTokenType
	(HashAlgos)(0),               // 26: models.v1alpha1.HashAlgos
}
var file_protos_models_v1alpha1_common_proto_depIdxs = []int32{
	2,  // 0: models.v1alpha1.SearchParam.search:type_name -> models.v1alpha1.MapList
	21, // 1: models.v1alpha1.SyncSchedule.frequency:type_name -> models.v1alpha1.Frequency
	4,  // 2: models.v1alpha1.ScheduleTab.syncTab:type_name -> models.v1alpha1.SyncSchedule
	22, // 3: models.v1alpha1.JWTParams.signingAlgorithm:type_name -> models.v1alpha1.EncryptionAlgo
	23, // 4: models.v1alpha1.JWTParams.status:type_name -> models.v1alpha1.CommonStatus
	24, // 5: models.v1alpha1.TlsConfig.tlsType:type_name -> models.v1alpha1.TlsType
	23, // 6: models.v1alpha1.SSLCerts.status:type_name -> models.v1alpha1.CommonStatus
	2,  // 7: models.v1alpha1.DMResponse.customMessage:type_name -> models.v1alpha1.MapList
	10, // 8: models.v1alpha1.DMResponse.agents:type_name -> models.v1alpha1.AgentShort
	11, // 9: models.v1alpha1.DynamicMessageUpdate.body:type_name -> models.v1alpha1.DynamicMessage
	25, // 10: models.v1alpha1.VapusCredentials.apiTokenType:type_name -> models.v1alpha1.ApiTokenType
	14, // 11: models.v1alpha1.VapusCredentials.awsCreds:type_name -> models.v1alpha1.AWSCreds
	15, // 12: models.v1alpha1.VapusCredentials.gcpCreds:type_name -> models.v1alpha1.GCPCreds
	16, // 13: models.v1alpha1.VapusCredentials.azureCreds:type_name -> models.v1alpha1.AzureCreds
	26, // 14: models.v1alpha1.DigestVal.algo:type_name -> models.v1alpha1.HashAlgos
	23, // 15: models.v1alpha1.AuthnOIDC.status:type_name -> models.v1alpha1.CommonStatus
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_protos_models_v1alpha1_common_proto_init() }
func file_protos_models_v1alpha1_common_proto_init() {
	if File_protos_models_v1alpha1_common_proto != nil {
		return
	}
	file_protos_models_v1alpha1_enums_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_protos_models_v1alpha1_common_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*SearchParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_models_v1alpha1_common_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Mapper); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_models_v1alpha1_common_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*MapList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_models_v1alpha1_common_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*BaseIdentifier); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_models_v1alpha1_common_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*SyncSchedule); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_models_v1alpha1_common_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*ScheduleTab); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_models_v1alpha1_common_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*JWTParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_models_v1alpha1_common_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*TlsConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_models_v1alpha1_common_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*SSLCerts); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_models_v1alpha1_common_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*DMResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_models_v1alpha1_common_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*AgentShort); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_models_v1alpha1_common_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*DynamicMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_models_v1alpha1_common_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*DynamicMessageUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_models_v1alpha1_common_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*VapusCredentials); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_models_v1alpha1_common_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*AWSCreds); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_models_v1alpha1_common_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*GCPCreds); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_models_v1alpha1_common_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*AzureCreds); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_models_v1alpha1_common_proto_msgTypes[17].Exporter = func(v any, i int) any {
			switch v := v.(*DigestVal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_models_v1alpha1_common_proto_msgTypes[18].Exporter = func(v any, i int) any {
			switch v := v.(*EmptyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_models_v1alpha1_common_proto_msgTypes[19].Exporter = func(v any, i int) any {
			switch v := v.(*AuthnOIDC); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_models_v1alpha1_common_proto_msgTypes[20].Exporter = func(v any, i int) any {
			switch v := v.(*Logs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_models_v1alpha1_common_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_models_v1alpha1_common_proto_goTypes,
		DependencyIndexes: file_protos_models_v1alpha1_common_proto_depIdxs,
		MessageInfos:      file_protos_models_v1alpha1_common_proto_msgTypes,
	}.Build()
	File_protos_models_v1alpha1_common_proto = out.File
	file_protos_models_v1alpha1_common_proto_rawDesc = nil
	file_protos_models_v1alpha1_common_proto_goTypes = nil
	file_protos_models_v1alpha1_common_proto_depIdxs = nil
}
