package utils

import "errors"

// Error constants
var (
	ErrInvalidManageAgentActions = errors.New("error - invalid goal requested for the agent")

	ErrGeneratingRequestFiles = errors.New("error while generating sample request files for vapusdata resources")
	ErrInvalidFileFormat      = errors.New("invalid file format requested for the goal")
	ErrDataStoreBoot          = errors.New("error while booting the data store")

	ErrUnAuthenticated                = errors.New("error while authenticating the user for generating platform access token")
	ErrUser404                        = errors.New("user not found")
	ErrUserUnMarshelling              = errors.New("error while unmarshelling user info")
	ErrUserInviteExpired              = errors.New("user invite expired for given user")
	ErrUserInvite                     = errors.New("error while inviting user")
	ErrUserDomain404                  = errors.New("error- invalid domain requested, user is not attached to requested domain")
	ErrUserInviteExists               = errors.New("error: invite for given user already exists")
	ErrGetUser404                     = errors.New("error while fetching user, user not found")
	ErrInvalidAccessTokenAgentUtility = errors.New("error - invalid access token utility requested")
	ErrAuthenticatorInitFailed        = errors.New("error while initializing authenticator for given OIDC provider")
	ErrLoginGeneration                = errors.New("error while generating login url for the user")
	ErrInvalidRequestObj              = errors.New("error - invalid spec name requested, please provide a valid spec name")

	ErrDMSecretStore        = errors.New("error while storing credentials in the vault")
	ErrInvalidDataMesh      = errors.New("error - invalid DataMesh")
	ErrInvalidDmNode        = errors.New("error - invalid Node ID for specified DataMesh")
	ErrDmAccessJwtPbKeySave = errors.New("error saving DataMesh Access JWT public key")
	ErrDmAccessJwtPbKeyRead = errors.New("error reading DataMesh Access JWT public key")
	ErrDmAccessJwtPvKeySave = errors.New("error savinf DataMesh Access JWT private key")

	ErrDataMeshInitialization      = errors.New("error while initiating DataMesh and saving configuration")
	ErrMeshIdentifier              = errors.New("error while generating DataMesh Identifier")
	ErrGracefulleDataMeshExist     = errors.New("error - DataMesh already exists, please use the DataMesh id and configure it")
	ErrGetDataMesh                 = errors.New("error while fetching DataMesh details")
	ErrInvalidDataMeshRequested    = errors.New("error - invalid DataMesh requested")
	ErrInvalidDataMeshAgentActions = errors.New("invalid action for the requested datamesh")

	ErrAccountCreation        = errors.New("error while creating account")
	ErrGetAccount             = errors.New("error while fetching account details")
	ErrInvalidAccount         = errors.New("invalid account id requested")
	ErrAccountAlreadyExists   = errors.New("account already exists for this setup")
	ErrAccountDataMeshMapping = errors.New("error while mapping DataMesh to account")
	ErrDataMeshIAccountAttach = errors.New("error while attaching DataMesh to the account")
	ErrSavingDataMeshInTable  = errors.New("error while saving DataMesh in the table")
	ErrInvalidMeshRequested   = errors.New("error - invalid DataMesh requested")

	ErrMarshellingNodeScheme = errors.New("error while marshelling node scheme")
	ErrIndexingNodeMetaData  = errors.New("error while indexing data source metadata")
	ErrESConfig404           = errors.New("error, elasticsearch config and credentials not found")
	ErrNoSecretStoreSelected = errors.New("error, no secret store is selected while booting the service")

	ErrNoPolicyFound = errors.New("error, no policies foujnd for the platform")

	ErrInvalidDataStore = errors.New("invalid DataStore for the platform")
	ErrNoCacherEnabled  = errors.New("no cacher is enabled for the platform")
	ErrInvalidDomain    = errors.New("error - invalid Domain")

	ErrDomainInitialization  = errors.New("error while initiating Domain and saving configuration")
	ErrDomainIdentifier      = errors.New("error while generating Domain Identifier")
	ErrGracefulleDomainExist = errors.New("error - domain already exists, please use the domain id and configure it")
	ErrGetDomain             = errors.New("error while fetching domain details")

	ErrAccountDomainMapping = errors.New("error while mapping domain to account")
	ErrUserDomainMapping    = errors.New("error while mapping domain to user")
	ErrDomainIAccountAttach = errors.New("error while attaching domain to the account")
	ErrSavingDomainInTable  = errors.New("error while saving domain in the table")

	ErrCreateDomain            = errors.New("error while creating domain")
	ErrDomainDomainMap         = errors.New("error while mapping domain to domain")
	ErrDomainDomainFirstMap    = errors.New("error while mapping domain to domain for the first source")
	ErrInvalidDomainRequested  = errors.New("error - invalid domain requested")
	ErrGetDomains              = errors.New("error while fetching domain")
	ErrSavingDomainsInTable    = errors.New("error while saving domain in the table")
	ErrAttachDomain            = errors.New("error while attaching domain to the domain")
	ErrSavingDomainAuthJwt     = errors.New("error while storing jwt keys for authentication")
	ErrDomain404               = errors.New("requested domain not found")
	ErrDomainArtifactStore404  = errors.New("error while fetching domain artifact store, domain artifact store not found")
	ErrGettingDomainAuthn      = errors.New("error while getting domain authentication details")
	ErrInvalidAddDomainRequest = errors.New("error - invalid domain spec requested")

	ErrCreateDataSource           = errors.New("error while creating data source")
	ErrGetDataSources             = errors.New("error while fetching data sources")
	ErrSavingDataSourceCreds      = errors.New("error while saving secret credentials for the data source")
	ErrDataSourceAttachError      = errors.New("error while attaching data source to the domain")
	ErrSavingDataSourcesInTable   = errors.New("error while saving datasources in the table")
	ErrInvalidDataSourceRequested = errors.New("error - while listing datasource")
	ErrDataSourceContentMapping   = errors.New("error while mapping the content of source in the domain")
	ErrDataSource403              = errors.New("error while accessing data source, forbidden access for the user")
	ErrMarshallingMetaData        = errors.New("error while marshalling metadata")

	ErrDataSourceSchemeDiscovery = errors.New("error while discovering the data source scheme")
	ErrDataSourceSchemeSaving    = errors.New("error while saving the data source scheme")
	ErrDataSourceCredsNotFound   = errors.New("no credentials found for the access scope")
	ErrDataSourceCredsSecretGet  = errors.New("error while getting the source cred secret from the vault")

	ErrDataCatalogCreationError       = errors.New("error while creating data catalog")
	ErrInvalidDataCatalogRequest      = errors.New("invalid data catalog spec in request")
	ErrInvalidDataCatalogAgentActions = errors.New("invalid goal for data catalog agent")
	ErrListingDataCatalog             = errors.New("error while listing data catalog, catalogs not found")

	ErrInvalidDataWorkerSpec  = errors.New("invalid data worker spec, missing or invalid fields present in the spec")
	ErrMissingDataWorkerSpec  = errors.New("no valid data worker spec is provided")
	ErrInvalidDataProductspec = errors.New("invalid data product spec, missing or invalid fields present in the spec")
	ErrMissingDataProductspec = errors.New("no valid data product spec is provided")

	ErrInvalidDataProductContainerSpec      = errors.New("invalid data workers in data products")
	ErrInvalidDataProductContainerSecrets   = errors.New("invalid data workers credentials in data products")
	ErrInvalidDataProductOwnerBuildAccess   = errors.New("requested user is not the current data product owner, so build process cannot go ahead")
	ErrBuildingDataProduct                  = errors.New("error while building data product")
	ErrInvalidContainerinDataProduct        = errors.New("error while parsing data worker in data product saving")
	ErrInvalidDataProductAccess             = errors.New("invalid data product request, current user doesn't have access")
	ErrMissingDataProductId                 = errors.New("data product id missing from the request")
	ErrDataProductNotRunning                = errors.New("error while deploying data product, it is not in built state")
	ErrDataProductDeploy                    = errors.New("error while deploying data product")
	ErrDataProductDeployAgent               = errors.New("error while initializing data product deploy agent")
	ErrDataProductNotInStateToBuild         = errors.New("error while building data product, it is not in valid state it should be in BUILT/CONFIGURED/WITHDREW state")
	ErrDataProductNotDeplyedForPublish      = errors.New("error while publishing data product, it is not in ready state")
	ErrInvalidDataProductOwnerPublishAccess = errors.New("requested user is not the current data product owner, so publish process cannot go ahead")
	ErrDataProduct404                       = errors.New("error while fetching data product, data product not found")
	ErrDataProductUser403                   = errors.New("error while accessing data product, forbidden access for the user")
	ErrConnectingDataProduct                = errors.New("error while connecting to data product, please check the status")
	ErrInvalidSearchType                    = errors.New("invalid search type requested")
	ErrSearchDataProducts404                = errors.New("error while searching data products, data products not found")
	ErrSearchDomainScheme404                = errors.New("error while searching domain scheme, domain scheme not found")
	ErrInvalidDataProductAgentActions       = errors.New("invalid goal for data product agent")
	ErrInvalidDataWorkerAgentActions        = errors.New("invalid goal for data worker agent")
	ErrDataProductNotPublishForDeploy       = errors.New("error while deploying data product, it is not in published state")
	ErrDataWorker403                        = errors.New("error while accessing data worker, forbidden access for the user")
	ErrDataProductSearch                    = errors.New("error while searching data product")
	ErrDataWorkerSyncPause                  = errors.New("error while pausing data worker sync")
	ErrSettingDomainK8SInfra                = errors.New("error while setting up domain k8s infra")
	ErrK8SInfra404                          = errors.New("error while fetching k8s infra, k8s infra not found")
	ErrInvalidStateForPauseDataWorker       = errors.New("error while pausing data worker, it is not in valid state")

	ErrInvalidAccountAgentActions      = errors.New("invalid goal for account agent")
	ErrGetCredsSecret                  = errors.New("error while getting the credentials from the secret store")
	ErrInvalidDomainArtifactStore      = errors.New("invalid artifact store for the domain")
	ErrCreateDomainCatalogIndex        = errors.New("error while creating domain catalog index")
	ErrPublishingDataProduct           = errors.New("error while publishing data product")
	Err403DataProductAccess            = errors.New("error while accessing data product, forbidden access for the user")
	Err404DeploymentSpec               = errors.New("error while fetching deployment spec, deployment spec not found")
	ErrInvalidObservabilityAgentModels = errors.New("invalid models for observability agent")
	ErrErrObservabilityData            = errors.New("error while fetching observability data")

	ErrAuthDataProduct  = errors.New("error while authenticating data product, access token not present in the request")
	ErrDataProductBuild = errors.New("error while building data product")
)
