# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos.aistudio.v1alpha1 import aistudio_pb2 as protos_dot_aistudio_dot_v1alpha1_dot_aistudio__pb2


class VapusAiStudioStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StudioSpaceInterface = channel.unary_unary(
                '/aistudio.v1alpha1.VapusAiStudio/StudioSpaceInterface',
                request_serializer=protos_dot_aistudio_dot_v1alpha1_dot_aistudio__pb2.StudioSpaceRequest.SerializeToString,
                response_deserializer=protos_dot_aistudio_dot_v1alpha1_dot_aistudio__pb2.StudioSpaceResponse.FromString,
                _registered_method=True)
        self.AIModelConfigurationInterface = channel.unary_unary(
                '/aistudio.v1alpha1.VapusAiStudio/AIModelConfigurationInterface',
                request_serializer=protos_dot_aistudio_dot_v1alpha1_dot_aistudio__pb2.AIModelConfigurationRequest.SerializeToString,
                response_deserializer=protos_dot_aistudio_dot_v1alpha1_dot_aistudio__pb2.AIModelConfigurationResponse.FromString,
                _registered_method=True)


class VapusAiStudioServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StudioSpaceInterface(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AIModelConfigurationInterface(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VapusAiStudioServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StudioSpaceInterface': grpc.unary_unary_rpc_method_handler(
                    servicer.StudioSpaceInterface,
                    request_deserializer=protos_dot_aistudio_dot_v1alpha1_dot_aistudio__pb2.StudioSpaceRequest.FromString,
                    response_serializer=protos_dot_aistudio_dot_v1alpha1_dot_aistudio__pb2.StudioSpaceResponse.SerializeToString,
            ),
            'AIModelConfigurationInterface': grpc.unary_unary_rpc_method_handler(
                    servicer.AIModelConfigurationInterface,
                    request_deserializer=protos_dot_aistudio_dot_v1alpha1_dot_aistudio__pb2.AIModelConfigurationRequest.FromString,
                    response_serializer=protos_dot_aistudio_dot_v1alpha1_dot_aistudio__pb2.AIModelConfigurationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aistudio.v1alpha1.VapusAiStudio', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aistudio.v1alpha1.VapusAiStudio', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VapusAiStudio(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StudioSpaceInterface(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aistudio.v1alpha1.VapusAiStudio/StudioSpaceInterface',
            protos_dot_aistudio_dot_v1alpha1_dot_aistudio__pb2.StudioSpaceRequest.SerializeToString,
            protos_dot_aistudio_dot_v1alpha1_dot_aistudio__pb2.StudioSpaceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AIModelConfigurationInterface(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aistudio.v1alpha1.VapusAiStudio/AIModelConfigurationInterface',
            protos_dot_aistudio_dot_v1alpha1_dot_aistudio__pb2.AIModelConfigurationRequest.SerializeToString,
            protos_dot_aistudio_dot_v1alpha1_dot_aistudio__pb2.AIModelConfigurationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
